#!/usr/bin/env python2
#coding=utf-8

import rospy #Crear nodos con ROS
from std_msgs.msg import Float64, String
import matplotlib.pyplot as plt
import threading
import time
import numpy
from copy import copy, deepcopy

SENSITIVITY_MAGN = (10.0*4800.0)/32768.0
offsets = [82.5, -9.5, 355.5]
offsets2 = [133.0, -94.0, 492.0] 
offsets3 = [26.0, 2.0, 494.5]

datos = numpy.zeros((299,4))
datos1 = numpy.zeros((299,4))
datos2 = numpy.zeros((299,4))
datos3 = numpy.zeros((299,4))


def grafica():
    global j, datos1, datos2, datos3

    fig, ax = plt.subplots()
    while j<299:
        print(j)
        ax.clear()
        ax.set_title(u'Magnetometro IMU1 calibrado XYZ')
        ax.set_xlabel(u'muestra')
        ax.scatter(datos[:j, 1], datos[:j, 2], label='MXY', color='blue', alpha=0.5)
        ax.scatter(datos[:j, 1], datos[:j, 3], label='MXZ', color='red', alpha=0.5)
        ax.scatter(datos[:j, 2], datos[:j, 3], label='MYZ', color='green', alpha=0.5)
        ax.legend(loc='best')
        plt.pause(0.01)
    print(datos1[:,:])
    print(datos2[:,:])
    print(datos3[:,:])    
    print(j)
    plt.show()
    j = 0
    print(j)

def callback(mensaje):

    global pub, j, datos1, datos2, datos3
    
    temp = mensaje.data.split(",")
    datos[j][:] = temp
    datos1[j][0] = datos[j,0]
    datos2[j][0] = datos[j,0]
    datos3[j][0] = datos[j,0]
    for i in range(0,3):
        datos1[j][i+1] = ((datos[j,i+1])-offsets[i])*SENSITIVITY_MAGN
        datos2[j][i+1] = ((datos[j,i+1])-offsets2[i])*SENSITIVITY_MAGN
        datos3[j][i+1] = ((datos[j,i+1])-offsets3[i])*SENSITIVITY_MAGN
    pub.publish(str(datos1[j,0])+","+str(datos1[j,1])+","+str(datos1[j,2])+","+str(datos1[j,3]))
    pub.publish(str(datos2[j,0])+","+str(datos2[j,1])+","+str(datos2[j,2])+","+str(datos2[j,3]))
    pub.publish(str(datos3[j,0])+","+str(datos3[j,1])+","+str(datos3[j,2])+","+str(datos3[j,3]))
    j+=1

def NPS_Magn_Cal_1():

    global pub, j

    j = 0

    rospy.init_node('NPS_Magn_Cal_1')

    pub = rospy.Publisher('m_xyz_c', String, queue_size=10)
    sub = rospy.Subscriber('m_xyz_sc', String, callback)

    rospy.spin()


if __name__ == '__main__':

    hilo2 = threading.Thread(target=grafica)
    hilo2.start()
    NPS_Magn_Cal_1()
